sudo: true
dist: xenial
language: python
python:
  - "3.6"

services:
- docker

branches:
  only:
    - master

env:
  - TF_INPUT=false

# Install terraform
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t namer-demo .
        - docker images
        - docker tag namer-demo $DOCKER_USERNAME/namer
        - docker push $DOCKER_USERNAME/namer
    - stage: integration testing
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker pull $DOCKER_USERNAME/namer
        - IP=$(hostname -I | awk '{ print $1 }')
        - URL=http://$IP:5000
        - mkdir -p ~/docker-data/mongodb
        - M_HOST=$IP docker-compose -f tools/docker-compose.yml up -d
        - M_HOST=$IP docker run -t $DOCKER_USERNAME/namer integrationtests -u $URL
        - docker-compose -f tools/docker-compose.yml down
