version: '3.7'

services:
  fix-mongodb-permissions:
    image: 'bitnami/mongodb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ~/docker-data/mongodb:/bitnami

  mongodb:
    environment:
      - MONGODB_USERNAME=$M_USERNAME
      - MONGODB_PASSWORD=$M_PASSWORD
      - MONGODB_DATABASE=${M_DB:-DB}
    image: 'bitnami/mongodb:latest'
    container_name: namer-db
    restart: always
    ports:
      - "${M_PORT:-27017}:${M_PORT:-27017}"
    volumes:
      - ~/docker-data/mongodb:/bitnami
    depends_on:
      - fix-mongodb-permissions
