version: '3.7'

services:
  mongodb:
    environment:
      - M_HOST=${M_HOST:-127.0.0.1}
      - M_PORT=27017
    image: 'bitnami/mongodb:latest'
    container_name: namer-db
    restart: always
    ports:
      - "${M_HOST:-127.0.0.1}:27017:27017"
