version: '3.7'

services:
  namer:
    environment:
      - M_DB=DB
      - M_HOST=${M_HOST:-127.0.0.1}
      - M_PORT=27017
    image: 'bzamilov/namer:latest'
    container_name: namer-app
    restart: always
    command: runserver
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
  
  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: namer-db
    restart: always
    ports:
      - "${M_HOST:-127.0.0.1}:27017:27017"