version: '3.7'

services:
  namer:
    environment:
      - M_DB=DB
      - M_HOST=${M_HOST}
      - M_PORT=27017
    image: 'bzamilov/namer:latest'
    container_name: namer-app
    restart: always
    command: runserver
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
  
  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: namer-db
    restart: always
    ports:
      - "27017:27017"
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 0
    #   #test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet | echo $?
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s